[General]
background=Assets/background.png
blurRadius=0

mPrimary=#ffb4a3
mOnPrimary=#621000
mSecondary=#ffb4a3
mOnSecondary=#522216
mTertiary=#e9c258
mOnTertiary=#3d2e00
mError=#ffb4ab
mOnError=#690005
mSurface=#1c110e
mOnSurface=#f4ded9
mSurfaceVariant=#291d1a
mOnSurfaceVariant=#dfc0b8
mOutline=#795b52
mShadow=#000000
mHover=#e9c258
mOnHover=#3d2e00
avatarPath=/home/black/Pictures/userpics-icons/393f3dde-77a0-4fff-8d7e-51cc1f7d6ded.jpeg
